//------------------------------------------------------------------------------
// <auto-generated>
//     Generated VSTO host item glue for the Visio application-level add-in.
// </auto-generated>
//------------------------------------------------------------------------------
#pragma warning disable 414
namespace LaTeXSnipper.Visio
{
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    [global::System.Security.Permissions.PermissionSetAttribute(global::System.Security.Permissions.SecurityAction.Demand, Name = "FullTrust")]
    public sealed partial class ThisAddIn : Microsoft.Office.Tools.AddInBase
    {
        internal Microsoft.Office.Interop.Visio.Application Application;

        public ThisAddIn(Microsoft.Office.Tools.Factory factory, global::System.IServiceProvider serviceProvider)
            : base(factory, serviceProvider, "AddIn", "ThisAddIn")
        {
            Globals.Factory = factory;
        }

        protected override void Initialize()
        {
            base.Initialize();
            Application = GetHostItem<Microsoft.Office.Interop.Visio.Application>(typeof(Microsoft.Office.Interop.Visio.Application), "Application");
            Globals.ThisAddIn = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
        }

        protected override void FinishInitialization()
        {
            InternalStartup();
            OnStartup();
        }

        protected override void InitializeDataBindings() { }
    }

    internal sealed class Globals
    {
        private Globals() { }
        private static ThisAddIn _thisAddIn;
        private static Microsoft.Office.Tools.Factory _factory;

        internal static ThisAddIn ThisAddIn
        {
            get { return _thisAddIn; }
            set { if (_thisAddIn == null) _thisAddIn = value; else throw new global::System.NotSupportedException(); }
        }

        internal static Microsoft.Office.Tools.Factory Factory
        {
            get { return _factory; }
            set { if (_factory == null) _factory = value; else throw new global::System.NotSupportedException(); }
        }

        internal static Microsoft.Office.Tools.Ribbon.RibbonCollectionBase Ribbons => null;
    }
}
