// Auto-generated by build-ole-version.ps1 from package.json (1.2.2).
// Do not edit manually 鈥?regenerate with: powershell -File scripts/build-ole-version.ps1

#ifndef OLE_VERSION_H
#define OLE_VERSION_H

#ifndef OLE_VERSION_MAJOR
#define OLE_VERSION_MAJOR 1
#endif

#ifndef OLE_VERSION_MINOR
#define OLE_VERSION_MINOR 2
#endif

#ifndef OLE_VERSION_PATCH
#define OLE_VERSION_PATCH 2
#endif

#ifndef OLE_VERSION_BUILD
#define OLE_VERSION_BUILD 0
#endif

// Comma-separated for FILEVERSION/PRODUCTVERSION macros
#define OLE_FILEVERSION_RAW OLE_VERSION_MAJOR,OLE_VERSION_MINOR,OLE_VERSION_PATCH,OLE_VERSION_BUILD
#define OLE_PRODUCTVERSION_RAW OLE_VERSION_MAJOR,OLE_VERSION_MINOR,OLE_VERSION_PATCH,OLE_VERSION_BUILD

// String for StringFileInfo
#define OLE_VERSION_STRING_A(major,minor,patch,build) #major "." #minor "." #patch "." #build
#define OLE_VERSION_STRING OLE_VERSION_STRING_A(OLE_VERSION_MAJOR,OLE_VERSION_MINOR,OLE_VERSION_PATCH,OLE_VERSION_BUILD)

#endif // OLE_VERSION_H
