// ------------------------------------------------------------------------------
//  <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace LaTeXSnipper.NativeOffice.Word.Ribbon
{
    partial class FormulaRibbon : Microsoft.Office.Tools.Ribbon.RibbonBase
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        public FormulaRibbon() : base(Globals.Factory.GetRibbonFactory())
        {
            InitializeComponent();
        }

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.tabLaTeXSnipper = this.Factory.CreateRibbonTab();
            this.groupFormula = this.Factory.CreateRibbonGroup();
            this.btnInsertInline = this.Factory.CreateRibbonButton();
            this.btnInsertDisplay = this.Factory.CreateRibbonButton();
            this.btnInsertNumbered = this.Factory.CreateRibbonButton();
            this.btnLoadFormula = this.Factory.CreateRibbonButton();
            this.btnDeleteFormula = this.Factory.CreateRibbonButton();
            this.groupNumbering = this.Factory.CreateRibbonGroup();
            this.btnInsertChapter = this.Factory.CreateRibbonButton();
            this.btnInsertSection = this.Factory.CreateRibbonButton();
            this.btnRenumber = this.Factory.CreateRibbonButton();
            this.btnInsertReference = this.Factory.CreateRibbonButton();
            this.groupTable = this.Factory.CreateRibbonGroup();
            this.btnLoadTable = this.Factory.CreateRibbonButton();
            this.btnInsertTable = this.Factory.CreateRibbonButton();
            this.groupFormat = this.Factory.CreateRibbonGroup();
            this.btnFormatSelection = this.Factory.CreateRibbonButton();
            this.btnFormatAll = this.Factory.CreateRibbonButton();
            this.groupTools = this.Factory.CreateRibbonGroup();
            this.btnOpenEditor = this.Factory.CreateRibbonButton();

            // tabLaTeXSnipper
            this.tabLaTeXSnipper.Groups.Add(this.groupFormula);
            this.tabLaTeXSnipper.Groups.Add(this.groupNumbering);
            this.tabLaTeXSnipper.Groups.Add(this.groupTable);
            this.tabLaTeXSnipper.Groups.Add(this.groupFormat);
            this.tabLaTeXSnipper.Groups.Add(this.groupTools);
            this.tabLaTeXSnipper.Label = "LaTeXSnipper";
            this.tabLaTeXSnipper.Name = "tabLaTeXSnipper";

            // groupFormula
            this.groupFormula.Items.Add(this.btnInsertInline);
            this.groupFormula.Items.Add(this.btnInsertDisplay);
            this.groupFormula.Items.Add(this.btnInsertNumbered);
            this.groupFormula.Items.Add(this.btnLoadFormula);
            this.groupFormula.Items.Add(this.btnDeleteFormula);
            this.groupFormula.Label = "Formula";
            this.groupFormula.Name = "groupFormula";

            // btnInsertInline
            this.btnInsertInline.Label = "Inline";
            this.btnInsertInline.Name = "btnInsertInline";
            this.btnInsertInline.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.btnInsertInline_Click);

            // btnInsertDisplay
            this.btnInsertDisplay.Label = "Display";
            this.btnInsertDisplay.Name = "btnInsertDisplay";
            this.btnInsertDisplay.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.btnInsertDisplay_Click);

            // btnInsertNumbered
            this.btnInsertNumbered.Label = "Numbered";
            this.btnInsertNumbered.Name = "btnInsertNumbered";
            this.btnInsertNumbered.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.btnInsertNumbered_Click);

            // btnLoadFormula
            this.btnLoadFormula.Label = "Load";
            this.btnLoadFormula.Name = "btnLoadFormula";
            this.btnLoadFormula.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.btnLoadFormula_Click);

            // btnDeleteFormula
            this.btnDeleteFormula.Label = "Delete";
            this.btnDeleteFormula.Name = "btnDeleteFormula";
            this.btnDeleteFormula.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.btnDeleteFormula_Click);

            // groupNumbering
            this.groupNumbering.Items.Add(this.btnInsertChapter);
            this.groupNumbering.Items.Add(this.btnInsertSection);
            this.groupNumbering.Items.Add(this.btnRenumber);
            this.groupNumbering.Items.Add(this.btnInsertReference);
            this.groupNumbering.Label = "Numbering";
            this.groupNumbering.Name = "groupNumbering";

            // btnInsertChapter
            this.btnInsertChapter.Label = "Chapter";
            this.btnInsertChapter.Name = "btnInsertChapter";
            this.btnInsertChapter.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.btnInsertChapter_Click);

            // btnInsertSection
            this.btnInsertSection.Label = "Section";
            this.btnInsertSection.Name = "btnInsertSection";
            this.btnInsertSection.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.btnInsertSection_Click);

            // btnRenumber
            this.btnRenumber.Label = "Renumber";
            this.btnRenumber.Name = "btnRenumber";
            this.btnRenumber.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.btnRenumber_Click);

            // btnInsertReference
            this.btnInsertReference.Label = "Reference";
            this.btnInsertReference.Name = "btnInsertReference";
            this.btnInsertReference.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.btnInsertReference_Click);

            // groupTable
            this.groupTable.Items.Add(this.btnLoadTable);
            this.groupTable.Items.Add(this.btnInsertTable);
            this.groupTable.Label = "Table";
            this.groupTable.Name = "groupTable";

            // btnLoadTable
            this.btnLoadTable.Label = "Load Table";
            this.btnLoadTable.Name = "btnLoadTable";
            this.btnLoadTable.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.btnLoadTable_Click);

            // btnInsertTable
            this.btnInsertTable.Label = "Insert Table";
            this.btnInsertTable.Name = "btnInsertTable";
            this.btnInsertTable.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.btnInsertTable_Click);

            // groupFormat
            this.groupFormat.Items.Add(this.btnFormatSelection);
            this.groupFormat.Items.Add(this.btnFormatAll);
            this.groupFormat.Label = "Format";
            this.groupFormat.Name = "groupFormat";

            // btnFormatSelection
            this.btnFormatSelection.Label = "Format";
            this.btnFormatSelection.Name = "btnFormatSelection";
            this.btnFormatSelection.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.btnFormatSelection_Click);

            // btnFormatAll
            this.btnFormatAll.Label = "Format All";
            this.btnFormatAll.Name = "btnFormatAll";
            this.btnFormatAll.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.btnFormatAll_Click);

            // groupTools
            this.groupTools.Items.Add(this.btnOpenEditor);
            this.groupTools.Label = "Tools";
            this.groupTools.Name = "groupTools";

            // btnOpenEditor
            this.btnOpenEditor.Label = "Open Editor";
            this.btnOpenEditor.Name = "btnOpenEditor";
            this.btnOpenEditor.Click += new Microsoft.Office.Tools.Ribbon.RibbonControlEventHandler(this.btnOpenEditor_Click);

            this.tabLaTeXSnipper.ControlId.ControlIdType = Microsoft.Office.Tools.Ribbon.RibbonControlIdType.Office;
            this.tabLaTeXSnipper.ControlId.OfficeId = "TabHome";
            this.Name = "FormulaRibbon";
            this.RibbonType = "Microsoft.Word.Document";
            this.OnLoad += new System.EventHandler<System.EventArgs>(this.FormulaRibbon_Load);
        }

        #endregion

        internal Microsoft.Office.Tools.Ribbon.RibbonTab tabLaTeXSnipper;
        internal Microsoft.Office.Tools.Ribbon.RibbonGroup groupFormula;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton btnInsertInline;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton btnInsertDisplay;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton btnInsertNumbered;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton btnLoadFormula;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton btnDeleteFormula;
        internal Microsoft.Office.Tools.Ribbon.RibbonGroup groupNumbering;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton btnInsertChapter;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton btnInsertSection;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton btnRenumber;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton btnInsertReference;
        internal Microsoft.Office.Tools.Ribbon.RibbonGroup groupTable;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton btnLoadTable;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton btnInsertTable;
        internal Microsoft.Office.Tools.Ribbon.RibbonGroup groupFormat;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton btnFormatSelection;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton btnFormatAll;
        internal Microsoft.Office.Tools.Ribbon.RibbonGroup groupTools;
        internal Microsoft.Office.Tools.Ribbon.RibbonButton btnOpenEditor;
    }
}
