# Read version from package.json (or accept -Version override) and generate OleVersion.h.
# Usage:
#   powershell -File scripts/build-ole-version.ps1
#   powershell -File scripts/build-ole-version.ps1 -Version 1.2.3

param(
    [string]$Version = ""
)

$ErrorActionPreference = "Stop"

$rootDir = Split-Path $PSScriptRoot -Parent

# Prefer explicit -Version parameter; fall back to package.json
if ([string]::IsNullOrWhiteSpace($Version)) {
    $packageJson = Resolve-Path (Join-Path $rootDir "package.json")
    $Version = (Get-Content $packageJson -Raw | ConvertFrom-Json).version
}

# Parse semver (strip any pre-release suffix like -test.1)
$match = [regex]::Match($Version, "^(\d+)\.(\d+)\.(\d+)")
if (-not $match.Success) {
    Write-Error "Cannot parse version: $Version"
    exit 1
}

$major = $match.Groups[1].Value
$minor = $match.Groups[2].Value
$patch = $match.Groups[3].Value

$outDir = Join-Path $rootDir "apps\native-office\LaTeXSnipper.OleFormulaObjectNative\res"
$outFile = Join-Path $outDir "OleVersion.h"

# Use ASCII-safe comment characters to avoid encoding issues
$content = @"
// Auto-generated by build-ole-version.ps1 -- do not edit manually.
// Source: $Version  Regenerate: powershell -File scripts/build-ole-version.ps1

#ifndef OLE_VERSION_H
#define OLE_VERSION_H

#ifndef OLE_VERSION_MAJOR
#define OLE_VERSION_MAJOR $major
#endif

#ifndef OLE_VERSION_MINOR
#define OLE_VERSION_MINOR $minor
#endif

#ifndef OLE_VERSION_PATCH
#define OLE_VERSION_PATCH $patch
#endif

#ifndef OLE_VERSION_BUILD
#define OLE_VERSION_BUILD 0
#endif

// Comma-separated for FILEVERSION/PRODUCTVERSION macros
#define OLE_FILEVERSION_RAW OLE_VERSION_MAJOR,OLE_VERSION_MINOR,OLE_VERSION_PATCH,OLE_VERSION_BUILD
#define OLE_PRODUCTVERSION_RAW OLE_VERSION_MAJOR,OLE_VERSION_MINOR,OLE_VERSION_PATCH,OLE_VERSION_BUILD

// Two-level stringize so macros expand before stringification
#define OLE_STRINGIZE_IMPL(x) #x
#define OLE_STRINGIZE(x) OLE_STRINGIZE_IMPL(x)

// Product version string for StringFileInfo
#define OLE_VERSION_STRING \
    OLE_STRINGIZE(OLE_VERSION_MAJOR) "." \
    OLE_STRINGIZE(OLE_VERSION_MINOR) "." \
    OLE_STRINGIZE(OLE_VERSION_PATCH) "." \
    OLE_STRINGIZE(OLE_VERSION_BUILD)

#endif // OLE_VERSION_H
"@

Set-Content -Path $outFile -Value $content -Encoding UTF8
Write-Host "Generated OleVersion.h: $major.$minor.$patch.0 (from $Version)"
