# Read version from root package.json and generate OleVersion.h for the OLE DLL.
# Usage: powershell -File scripts/build-ole-version.ps1

$ErrorActionPreference = "Stop"

$rootDir = Split-Path $PSScriptRoot -Parent
$packageJson = Resolve-Path (Join-Path $rootDir "package.json")
$version = (Get-Content $packageJson -Raw | ConvertFrom-Json).version

# Parse semver (strip any pre-release suffix like -test.1)
$match = [regex]::Match($version, "^(\d+)\.(\d+)\.(\d+)")
if (-not $match.Success) {
    Write-Error "Cannot parse version from package.json: $version"
    exit 1
}

$major = $match.Groups[1].Value
$minor = $match.Groups[2].Value
$patch = $match.Groups[3].Value

$outDir = Join-Path $rootDir "apps\native-office\LaTeXSnipper.OleFormulaObjectNative\res"
$outFile = Join-Path $outDir "OleVersion.h"

$content = @"
// Auto-generated by build-ole-version.ps1 from package.json ($version).
// Do not edit manually — regenerate with: powershell -File scripts/build-ole-version.ps1

#ifndef OLE_VERSION_H
#define OLE_VERSION_H

#ifndef OLE_VERSION_MAJOR
#define OLE_VERSION_MAJOR $major
#endif

#ifndef OLE_VERSION_MINOR
#define OLE_VERSION_MINOR $minor
#endif

#ifndef OLE_VERSION_PATCH
#define OLE_VERSION_PATCH $patch
#endif

#ifndef OLE_VERSION_BUILD
#define OLE_VERSION_BUILD 0
#endif

// Comma-separated for FILEVERSION/PRODUCTVERSION macros
#define OLE_FILEVERSION_RAW OLE_VERSION_MAJOR,OLE_VERSION_MINOR,OLE_VERSION_PATCH,OLE_VERSION_BUILD
#define OLE_PRODUCTVERSION_RAW OLE_VERSION_MAJOR,OLE_VERSION_MINOR,OLE_VERSION_PATCH,OLE_VERSION_BUILD

// String for StringFileInfo
#define OLE_VERSION_STRING_A(major,minor,patch,build) #major "." #minor "." #patch "." #build
#define OLE_VERSION_STRING OLE_VERSION_STRING_A(OLE_VERSION_MAJOR,OLE_VERSION_MINOR,OLE_VERSION_PATCH,OLE_VERSION_BUILD)

#endif // OLE_VERSION_H
"@

Set-Content -Path $outFile -Value $content -Encoding UTF8
Write-Host "Generated OleVersion.h: $major.$minor.$patch.0 (from package.json $version)"
