#nullable enable
using System.Globalization;
using System.Collections.Generic;

namespace LaTeXSnipper.NativeOffice.Shared;

/// <summary>
/// Provides localized strings for Ribbon UI elements.
/// Uses Thread.CurrentThread.CurrentUICulture to select language.
/// </summary>
public static class RibbonLocalizer
{
    private static readonly Dictionary<string, Dictionary<string, string>> _strings = new()
    {
        ["en-US"] = new()
        {
            ["TabLabel"] = "LaTeXSnipper",
            ["LaTeXSnipperTab"] = "LaTeXSnipper",
            ["LaTeXSnipperPPTTab"] = "LaTeXSnipper",
            ["LaTeXSnipperExcelTab"] = "LaTeXSnipper",
            ["FormulaGroup"] = "Create",
            ["EditGroup"] = "Selection",
            ["WorkspaceGroup"] = "Workspaces",
            ["ToolsGroup"] = "Convert & Tools",
            ["btnInsertInline"] = "Insert Inline",
            ["btnInsertInline_screentip"] = "Insert Inline Formula",
            ["btnInsertInline_supertip"] = "Insert an inline LaTeX formula at cursor.",
            ["btnInsertDisplay"] = "Insert Display",
            ["btnInsertDisplay_screentip"] = "Insert Display Formula",
            ["btnInsertDisplay_supertip"] = "Insert a displayed LaTeX formula centered on its own line.",
            ["btnInsertNumbered"] = "Insert Numbered",
            ["btnInsertNumbered_screentip"] = "Insert Numbered Formula",
            ["btnInsertNumbered_supertip"] = "Insert a displayed formula with auto-numbering.",
            ["btnInsertFormula"] = "Insert Formula",
            ["btnInsertFormula_screentip"] = "Insert LaTeX Formula",
            ["btnInsertFormula_supertip"] = "Insert LaTeX as image or OLE object.",
            ["btnOcrSelector"] = "Screenshot OCR",
            ["btnOcrSelector_screentip"] = "Screen Capture OCR",
            ["btnOcrSelector_supertip"] = "Screenshot and convert to LaTeX via OCR.",
            ["btnLoadSelected"] = "Edit Selection",
            ["btnLoadSelected_screentip"] = "Edit Selected Formula",
            ["btnLoadSelected_supertip"] = "Load the selected formula into LaTeXSnipper for editing.",
            ["btnDeleteSelected"] = "Delete Selection",
            ["btnDeleteSelected_screentip"] = "Delete Formula",
            ["btnDeleteSelected_supertip"] = "Delete the selected formula from the document.",
            ["btnShowTaskPane"] = "Open Workspace",
            ["btnShowTaskPane_screentip"] = "Open LaTeXSnipper Workspace",
            ["btnShowTaskPane_supertip"] = "Open the LaTeXSnipper workspace for advanced editing.",
            ["btnFormulaLibrary"] = "Formula Library",
            ["btnFormulaLibrary_screentip"] = "Open Formula Library",
            ["btnFormulaLibrary_supertip"] = "Browse built-in formulas and your saved custom symbols.",
            ["btnDrawingWorkspace"] = "Drawing",
            ["btnDrawingWorkspace_screentip"] = "Open Drawing Workspace",
            ["btnDrawingWorkspace_supertip"] = "Create SVG, TikZ, PGFPlots, Graphviz, and Mermaid drawings.",
            ["btnRecognitionWorkspace"] = "Recognition",
            ["btnRecognitionWorkspace_screentip"] = "Open Recognition Workspace",
            ["btnRecognitionWorkspace_supertip"] = "Recognize formulas from screenshots, images, and PDF files.",
            ["btnBatchConvert"] = "Batch Convert",
            ["btnSelectionLatex"] = "Selection as LaTeX",
            ["btnSelectionLatex_screentip"] = "Preview selected LaTeX",
            ["btnSelectionLatex_supertip"] = "Select one formula, with or without delimiters. Preview and confirm before replacing text; errors keep the original.",
            ["btnBatchConvert_screentip"] = "Open Batch Conversion",
            ["btnBatchConvert_supertip"] = "Scan the current document and convert LaTeX in bounded, recoverable batches.",
            ["btnFormulaConvert"] = "Formula Convert",
            ["btnFormulaConvert_screentip"] = "Convert Formula Formats",
            ["btnFormulaConvert_supertip"] = "Preview and confirm a supported format. Word managed formulas: OMML/OLE; editor copies: LaTeX/OMML/SVG/PNG. Unsupported targets explain why.",
            ["btnOfficeWorkspace"] = "Office Tools",
            ["btnOfficeWorkspace_screentip"] = "Open Office Workspace",
            ["btnOfficeWorkspace_supertip"] = "Manage insertion routes, document actions, and Office sessions.",
            ["btnDiagnostics"] = "Diagnostics",
            ["btnDiagnostics_screentip"] = "Open Diagnostics",
            ["btnDiagnostics_supertip"] = "Inspect Core, runtime, drawing, bridge, and Office readiness.",
            ["btnSettings"] = "Settings",
            ["btnSettings_screentip"] = "LaTeXSnipper Settings",
            ["btnSettings_supertip"] = "Configure integration mode and preferences.",
            ["btnHelp"] = "Help",
            ["btnHelp_screentip"] = "LaTeXSnipper Help",
            ["btnHelp_supertip"] = "Version info and documentation links.",
            ["NoFormulaSelected"] = "No formula selected",
            ["FormulaDeleted"] = "Formula deleted",
            ["NotImplemented"] = "Not implemented",
            ["ErrorTitle"] = "LaTeXSnipper",
            ["ErrorOleNotAvailable"] = "OLE mode is not available on this system.",
            ["ErrorOleInitFailed"] = "Failed to initialize OLE formula object.",
            ["ErrorFallbackImage"] = "Rendering unavailable; check Desktop is running.",
            ["ErrorContextChanged"] = "Document context changed — please retry.",
            ["ErrorNoRenderData"] = "No image data for the current storage mode.",
            ["HelpText"] = "LaTeXSnipper v1.0.0\nNative Office plugin for Word, Excel, PowerPoint, and Visio.",
            ["ReadFormulaPrefix"] = "LaTeX: ",
            ["ErrorPrefix"] = "Error: ",
        },
        ["zh-CN"] = new()
        {
            ["TabLabel"] = "LaTeXSnipper",
            ["LaTeXSnipperTab"] = "LaTeXSnipper",
            ["LaTeXSnipperPPTTab"] = "LaTeXSnipper",
            ["LaTeXSnipperExcelTab"] = "LaTeXSnipper",
            ["FormulaGroup"] = "创建",
            ["EditGroup"] = "选中公式",
            ["WorkspaceGroup"] = "功能工作区",
            ["ToolsGroup"] = "转换与工具",
            ["btnInsertInline"] = "插入行内公式",
            ["btnInsertInline_screentip"] = "插入行内公式",
            ["btnInsertInline_supertip"] = "在光标位置插入行内 LaTeX 公式。",
            ["btnInsertDisplay"] = "插入显示公式",
            ["btnInsertDisplay_screentip"] = "插入显示公式",
            ["btnInsertDisplay_supertip"] = "插入居中显示的 LaTeX 公式。",
            ["btnInsertNumbered"] = "插入编号公式",
            ["btnInsertNumbered_screentip"] = "插入编号公式",
            ["btnInsertNumbered_supertip"] = "插入带自动编号的显示公式。",
            ["btnInsertFormula"] = "插入公式",
            ["btnInsertFormula_screentip"] = "插入 LaTeX 公式",
            ["btnInsertFormula_supertip"] = "以图片或 OLE 对象插入 LaTeX 公式。",
            ["btnOcrSelector"] = "屏幕识别",
            ["btnOcrSelector_screentip"] = "屏幕截图识别",
            ["btnOcrSelector_supertip"] = "截取屏幕区域并使用 OCR 转为 LaTeX。",
            ["btnLoadSelected"] = "编辑选中公式",
            ["btnLoadSelected_screentip"] = "编辑选中公式",
            ["btnLoadSelected_supertip"] = "将选中公式加载到 LaTeXSnipper 继续编辑。",
            ["btnDeleteSelected"] = "删除选中公式",
            ["btnDeleteSelected_screentip"] = "删除公式",
            ["btnDeleteSelected_supertip"] = "从文档中删除当前选中的公式。",
            ["btnShowTaskPane"] = "打开工作区",
            ["btnShowTaskPane_screentip"] = "打开 LaTeXSnipper 工作区",
            ["btnShowTaskPane_supertip"] = "打开 LaTeXSnipper 工作区进行高级编辑。",
            ["btnFormulaLibrary"] = "公式库",
            ["btnFormulaLibrary_screentip"] = "打开公式库",
            ["btnFormulaLibrary_supertip"] = "浏览内置公式以及自己保存的自定义符号。",
            ["btnDrawingWorkspace"] = "绘图",
            ["btnDrawingWorkspace_screentip"] = "打开绘图工作区",
            ["btnDrawingWorkspace_supertip"] = "创建 SVG、TikZ、PGFPlots、Graphviz 与 Mermaid 绘图。",
            ["btnRecognitionWorkspace"] = "识别中心",
            ["btnRecognitionWorkspace_screentip"] = "打开识别工作区",
            ["btnRecognitionWorkspace_supertip"] = "从截图、图片和 PDF 中识别公式。",
            ["btnBatchConvert"] = "批量转换",
            ["btnSelectionLatex"] = "选区作为 LaTeX",
            ["btnSelectionLatex_screentip"] = "预览选区中的 LaTeX",
            ["btnSelectionLatex_supertip"] = "先在 Word 中选中一条公式，无需分隔符。预览并确认后才替换；失败保留原文。",
            ["btnBatchConvert_screentip"] = "打开批量转换",
            ["btnBatchConvert_supertip"] = "扫描当前文档，并用分块、可恢复方式转换 LaTeX。",
            ["btnFormulaConvert"] = "公式转换",
            ["btnFormulaConvert_screentip"] = "转换公式格式",
            ["btnFormulaConvert_supertip"] = "先预览再确认。Word 本应用公式可选 OMML/OLE；编辑器副本可导出 LaTeX/OMML/SVG/PNG，不可用目标会说明原因。",
            ["btnOfficeWorkspace"] = "Office 工具",
            ["btnOfficeWorkspace_screentip"] = "打开 Office 工作区",
            ["btnOfficeWorkspace_supertip"] = "管理插入路线、文档操作与 Office 会话。",
            ["btnDiagnostics"] = "诊断",
            ["btnDiagnostics_screentip"] = "打开诊断工作区",
            ["btnDiagnostics_supertip"] = "检查 Core、运行时、绘图、桥接和 Office 就绪状态。",
            ["btnSettings"] = "设置",
            ["btnSettings_screentip"] = "LaTeXSnipper 设置",
            ["btnSettings_supertip"] = "配置集成模式和偏好。",
            ["btnHelp"] = "帮助",
            ["btnHelp_screentip"] = "LaTeXSnipper 帮助",
            ["btnHelp_supertip"] = "查看版本信息和文档链接。",
            ["NoFormulaSelected"] = "未选中公式",
            ["FormulaDeleted"] = "公式已删除",
            ["NotImplemented"] = "未实现",
            ["ErrorTitle"] = "LaTeXSnipper",
            ["ErrorOleNotAvailable"] = "当前系统不支持 OLE 模式。",
            ["ErrorOleInitFailed"] = "OLE 公式对象初始化失败。",
            ["ErrorFallbackImage"] = "渲染不可用，请检查桌面端是否运行。",
            ["ErrorContextChanged"] = "文档上下文已变更，请重试。",
            ["ErrorNoRenderData"] = "当前存储模式没有可用图像数据。",
            ["HelpText"] = "LaTeXSnipper v1.0.0\nWord、Excel、PowerPoint、Visio 的原生 Office 公式插件。",
            ["ReadFormulaPrefix"] = "LaTeX: ",
            ["ErrorPrefix"] = "错误: ",
        },
    };

    public static string GetString(string key)
    {
        var culture = CultureInfo.CurrentUICulture.Name;
        if (_strings.TryGetValue(culture, out var table) && table.TryGetValue(key, out var value))
            return value;

        // Fallback to en-US
        if (_strings.TryGetValue("en-US", out var enTable) && enTable.TryGetValue(key, out var enValue))
            return enValue;

        return key;
    }
}
